/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restoransistemi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ewnS
 */
public class Garsongiris extends javax.swing.JFrame {

    
   
    public Garsongiris() {
        initComponents();
        
    }
    int mouseX;
    int mouseY;
    sqlsettings sqlayar=new sqlsettings();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pastxt = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        cikisadmin = new javax.swing.JLabel();
        girisgeri = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        adminsurukle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Girişi");
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Gotham Narrow Book", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Kullanıcı Adı");

        nametxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        nametxt.setForeground(new java.awt.Color(51, 51, 51));
        nametxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel6.setFont(new java.awt.Font("Gotham XNarrow Book", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Sifre");

        pastxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        pastxt.setForeground(new java.awt.Color(51, 51, 51));
        pastxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jButton1.setBackground(new java.awt.Color(204, 59, 16));
        jButton1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Giriş");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cikisadmin.setBackground(new java.awt.Color(204, 59, 16));
        cikisadmin.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        cikisadmin.setForeground(new java.awt.Color(255, 255, 255));
        cikisadmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cikisadmin.setText("x");
        cikisadmin.setOpaque(true);
        cikisadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cikisadminMouseClicked(evt);
            }
        });

        girisgeri.setBackground(new java.awt.Color(255, 255, 255));
        girisgeri.setFont(new java.awt.Font("Gotham Narrow Bold", 0, 24)); // NOI18N
        girisgeri.setForeground(new java.awt.Color(255, 255, 255));
        girisgeri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/geri.png"))); // NOI18N
        girisgeri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                girisgeriMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(girisgeri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cikisadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(173, 173, 173))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nametxt)
                        .addComponent(pastxt, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cikisadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(girisgeri))
                .addGap(55, 55, 55)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pastxt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(560, 110, 290, 360);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Gotham Narrow Light", 0, 70)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Giriş");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 290, 140, 80);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Gotham Narrow Black", 0, 100)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Garson");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 190, 330, 120);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/arkaplan.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 950, 560);

        adminsurukle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                adminsurukleMouseDragged(evt);
            }
        });
        adminsurukle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                adminsurukleMousePressed(evt);
            }
        });
        getContentPane().add(adminsurukle);
        adminsurukle.setBounds(0, 0, 940, 29);

        setSize(new java.awt.Dimension(940, 559));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        
          //GİRİŞ YAPMA
        
        char[] sifretxt=pastxt.getPassword();
         String password=new String(sifretxt);
       
        try{
            Class.forName(sqlayar.Driver);
            Connection con=DriverManager.getConnection(sqlayar.url, sqlayar.user, sqlayar.pass);
            String sql="Select * from userlogin where ad=? and sifre=?";         
            PreparedStatement pst=con.prepareStatement(sql);
            
             pst.setString(1,nametxt.getText());
              pst.setString(2,password);
              
               String name=nametxt.getText();
              if(name.equals("")){
                   JOptionPane.showMessageDialog(this,"Kullanıcı adı boş bırakılamaz. ");
              }
              else{
            ResultSet rs=pst.executeQuery();

             if(rs.next()){
                  
                  new IslemPanel().setVisible(true);
                  this.setVisible(false);
             }
             else{
                  JOptionPane.showMessageDialog(this,"Kullanıcı adı veya Şifre yanlış. ");
             }
              }
             
             
        }catch(Exception e){
             JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cikisadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cikisadminMouseClicked
        //cıkış tuşu
       int uyarı= JOptionPane.showConfirmDialog(this,"Cıkış Yapılsın mı ?","Uyarı!",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(uyarı==JOptionPane.YES_OPTION){
            System.exit(0);
        }
       
    }//GEN-LAST:event_cikisadminMouseClicked

    private void adminsurukleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminsurukleMouseDragged
       //paneli hareket ettirmek icin gerekli kod
        int kordinatX=evt.getXOnScreen();
        int kordinatY=evt.getYOnScreen();
        
        this.setLocation(kordinatX-mouseX,kordinatY-mouseY);
    }//GEN-LAST:event_adminsurukleMouseDragged

    private void adminsurukleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminsurukleMousePressed
      mouseX=evt.getX();
       mouseY=evt.getY();
    }//GEN-LAST:event_adminsurukleMousePressed

    private void girisgeriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_girisgeriMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Giris().setVisible(true);
            
              
    }//GEN-LAST:event_girisgeriMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Garsongiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Garsongiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Garsongiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Garsongiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Garsongiris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminsurukle;
    private javax.swing.JLabel cikisadmin;
    private javax.swing.JLabel girisgeri;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField nametxt;
    private javax.swing.JPasswordField pastxt;
    // End of variables declaration//GEN-END:variables
}
