/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restoransistemi;

import javax.swing.JOptionPane;

/**
 *
 * @author ewnS
 */
public class Giris extends javax.swing.JFrame {

    int mouseX;
    int mouseY;
   
    public Giris() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cikisadmin = new javax.swing.JLabel();
        adminsurukle = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        garsongiris = new javax.swing.JLabel();
        admingiris = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Girişi");
        setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Admin Giriş");

        cikisadmin.setBackground(new java.awt.Color(204, 59, 16));
        cikisadmin.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        cikisadmin.setForeground(new java.awt.Color(255, 255, 255));
        cikisadmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cikisadmin.setText("x");
        cikisadmin.setOpaque(true);
        cikisadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cikisadminMouseClicked(evt);
            }
        });

        adminsurukle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                adminsurukleMouseDragged(evt);
            }
        });
        adminsurukle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                adminsurukleMousePressed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Garson Giriş");

        garsongiris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/garson.png"))); // NOI18N
        garsongiris.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                garsongirisMouseClicked(evt);
            }
        });

        admingiris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/admin.png"))); // NOI18N
        admingiris.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admingirisMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(adminsurukle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cikisadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel4)
                .addGap(49, 49, 49)
                .addComponent(jLabel5)
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(admingiris)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(garsongiris)
                .addGap(106, 106, 106))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cikisadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminsurukle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(admingiris)
                    .addComponent(garsongiris))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(634, 374));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cikisadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cikisadminMouseClicked
        //cıkış tuşu
       int uyarı= JOptionPane.showConfirmDialog(this,"Cıkış Yapılsın mı ?","Uyarı!",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(uyarı==JOptionPane.YES_OPTION){
            System.exit(0);
        }
       
    }//GEN-LAST:event_cikisadminMouseClicked

    private void adminsurukleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminsurukleMouseDragged
       //paneli hareket ettirmek icin gerekli kod
        int kordinatX=evt.getXOnScreen();
        int kordinatY=evt.getYOnScreen();
        
        this.setLocation(kordinatX-mouseX,kordinatY-mouseY);
    }//GEN-LAST:event_adminsurukleMouseDragged

    private void adminsurukleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminsurukleMousePressed
      mouseX=evt.getX();
       mouseY=evt.getY();
    }//GEN-LAST:event_adminsurukleMousePressed

    private void admingirisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admingirisMouseClicked
        // TODO add your handling code here:
        new Admingiris().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_admingirisMouseClicked

    private void garsongirisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_garsongirisMouseClicked
        // TODO add your handling code here:
        new Garsongiris().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_garsongirisMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Giris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admingiris;
    private javax.swing.JLabel adminsurukle;
    private javax.swing.JLabel cikisadmin;
    private javax.swing.JLabel garsongiris;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
