/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package restoransistemi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ewnS
 */
public class IslemPanel extends javax.swing.JFrame {

   int mouseX;
   int mouseY;
   
    public IslemPanel() {
        initComponents();
        //masa ve urun fonksiyonları program başladığında cağırmamız lazım.
        show_masa();
        show_urun();
    }
    
   //sql class cağırma
    sqlsettings sqlayar=new sqlsettings();

   //masaları listelemek icin
    public ArrayList<Masa> masaList(){
        ArrayList<Masa> usersList= new ArrayList<>();
         try{
            Class.forName(sqlayar.Driver);
            Connection con=DriverManager.getConnection(sqlayar.url, sqlayar.user, sqlayar.pass);
            String sqlsorgu="Select * from Masalar ";  
          
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(sqlsorgu);
         
            Masa masa;
          
            while(rs.next()){
                masa=new Masa(rs.getString("Masano"),rs.getInt("fiyat"));
           usersList.add(masa);
            }

        }catch(Exception e){
             JOptionPane.showMessageDialog(this,e.getMessage());
        }
         return usersList;
    }
    public void show_masa(){
        ArrayList<Masa> list= masaList();
        DefaultTableModel model= (DefaultTableModel)masabilgitbl.getModel();
        Object[] row= new Object[2];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getname();
            row[1]=list.get(i).gethesap();
            model.addRow(row);
        }
    }
    
    
    //ürünleri listelemek icin
     public ArrayList<urunler> urunList(){
            ArrayList<urunler> urunList= new ArrayList<>();
         try{
            Class.forName(sqlayar.Driver);
            Connection con=DriverManager.getConnection(sqlayar.url, sqlayar.user, sqlayar.pass);
            String sqlsorgu="Select * from ürünler ";  
          
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(sqlsorgu);
         
            urunler urun;
          
            while(rs.next()){
                urun=new urunler(rs.getString("urunbilgisi"),rs.getInt("fiyat"));
           urunList.add(urun);
            }

        }catch(Exception e){
             JOptionPane.showMessageDialog(this,e.getMessage());
        }
         return urunList;
    }
      public void show_urun(){
        ArrayList<urunler> list= urunList();
        DefaultTableModel model= (DefaultTableModel)uruntbl.getModel();
        Object[] row= new Object[6];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).geturun();
            row[1]=list.get(i).gethesap();
            model.addRow(row);
        }
    }
      
      
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        masabilgitbl = new javax.swing.JTable();
        masaaditxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        uruntbl = new javax.swing.JTable();
        hesaptxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        uruntxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        adettxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fiyattxt = new javax.swing.JTextField();
        hesapekle = new javax.swing.JButton();
        hesapkapatbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cikismasa = new javax.swing.JLabel();
        girisgit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Masalar");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        masabilgitbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Masa", "Hesap Tutarı"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        masabilgitbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masabilgitblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(masabilgitbl);

        masaaditxt.setEditable(false);
        masaaditxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        masaaditxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 59, 16));
        jLabel1.setText("Masa :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 59, 16));
        jLabel2.setText("Hesap:");

        uruntbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ürün Acıklama", "Fiyat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        uruntbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uruntblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(uruntbl);
        if (uruntbl.getColumnModel().getColumnCount() > 0) {
            uruntbl.getColumnModel().getColumn(0).setMinWidth(300);
            uruntbl.getColumnModel().getColumn(0).setMaxWidth(300);
        }

        hesaptxt.setEditable(false);
        hesaptxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hesaptxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jPanel3.setBackground(new java.awt.Color(204, 59, 16));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ürün:");

        uruntxt.setEditable(false);
        uruntxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        uruntxt.setForeground(new java.awt.Color(51, 51, 51));
        uruntxt.setBorder(null);

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fiyat:");

        adettxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        adettxt.setForeground(new java.awt.Color(51, 51, 51));
        adettxt.setText("1");
        adettxt.setBorder(null);
        adettxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adettxtActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Adet:");

        fiyattxt.setEditable(false);
        fiyattxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        fiyattxt.setForeground(new java.awt.Color(51, 51, 51));
        fiyattxt.setBorder(null);

        hesapekle.setText("Hesaba Ekle");
        hesapekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hesapekleActionPerformed(evt);
            }
        });

        hesapkapatbtn.setText("Hesabı Kapat");
        hesapkapatbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hesapkapatbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uruntxt)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(11, 11, 11)
                        .addComponent(adettxt))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hesapekle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fiyattxt)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(hesapkapatbtn)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(uruntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(adettxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fiyattxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hesapekle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hesapkapatbtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(masaaditxt, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hesaptxt))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(masaaditxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hesaptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 59, 16));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        cikismasa.setBackground(new java.awt.Color(204, 59, 16));
        cikismasa.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        cikismasa.setForeground(new java.awt.Color(255, 255, 255));
        cikismasa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cikismasa.setText("x");
        cikismasa.setOpaque(true);
        cikismasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cikismasaMouseClicked(evt);
            }
        });

        girisgit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/kilit.png"))); // NOI18N
        girisgit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                girisgitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(girisgit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cikismasa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(girisgit)
                    .addComponent(cikismasa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(941, 560));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cikismasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cikismasaMouseClicked
        int uyarı= JOptionPane.showConfirmDialog(this,"Cıkış Yapılsın mı ?","Uyarı!",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(uyarı==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_cikismasaMouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int kordinatX=evt.getXOnScreen();
        int kordinatY=evt.getYOnScreen();
        
        this.setLocation(kordinatX-mouseX,kordinatY-mouseY);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
       mouseX=evt.getX();
       mouseY=evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void girisgitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_girisgitMouseClicked
        // TODO add your handling code here:
        new Giris().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_girisgitMouseClicked

    private void masabilgitblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masabilgitblMouseClicked
        //Masa tablosundan masayı secme
      
        int i =masabilgitbl.getSelectedRow();
        TableModel model=masabilgitbl.getModel();
        masaaditxt.setText(model.getValueAt(i,0).toString());
        hesaptxt.setText(model.getValueAt(i,1).toString());
           
        
    }//GEN-LAST:event_masabilgitblMouseClicked

    private void uruntblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uruntblMouseClicked
        // Urunleri secme click olayı
        int i =uruntbl.getSelectedRow();
        TableModel model=uruntbl.getModel();
        uruntxt.setText(model.getValueAt(i,0).toString());
        fiyattxt.setText(model.getValueAt(i,1).toString());
        adettxt.setText("1");
        
    }//GEN-LAST:event_uruntblMouseClicked

    private void adettxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adettxtActionPerformed
        

        //Adeti fiyatla carpmamız gerekiyor 
        //string tipindeki veriyi int'e cevirip capıyoruz
        int fiyat=Integer.parseInt(fiyattxt.getText());
         int adet=Integer.parseInt(adettxt.getText());
        
        String carp=String.valueOf(fiyat*adet);
        fiyattxt.setText(carp);
        
        
    }//GEN-LAST:event_adettxtActionPerformed

    private void hesapekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hesapekleActionPerformed
        // TODO add your handling code here:
        try{
            
            //Veritabanı bağlantısı
            Class.forName(sqlayar.Driver);
            Connection con=DriverManager.getConnection(sqlayar.url, sqlayar.user, sqlayar.pass);
         
            String sql="update Masalar set fiyat=? where Masano=?";  //sorgu
            
            //hesaba fiyat ekleme
            int fiyat=Integer.parseInt(hesaptxt.getText());
            int ekle=Integer.parseInt(fiyattxt.getText());
           String hesap=String.valueOf(fiyat+ekle);
           
        
            PreparedStatement pst=con.prepareStatement(sql);
             pst.setString(1,hesap);
             pst.setString(2,masaaditxt.getText());
             
            
             String name=fiyattxt.getText();
              if(name.equals("")){//eklenicek fiyat boş ise uyarı vericek.
                   JOptionPane.showMessageDialog(this,"Hesaba ne kadar ekleniceğini belirleyiniz. ");
              }
              else{//masa ya hesap eklenmede bi sıkıntı yoksa calışıcak kodlar
            
               pst.executeUpdate();
               DefaultTableModel model= (DefaultTableModel)masabilgitbl.getModel();
             //model.setColumnCount(0);
             model.setRowCount(0);
              show_masa();
            
             
           
              }
        }catch(Exception e){
             JOptionPane.showMessageDialog(this,e.getMessage());//eğer bir hata alırsak calışıcak kod.
        }
    }//GEN-LAST:event_hesapekleActionPerformed

    private void hesapkapatbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hesapkapatbtnActionPerformed
       
        //hesap kapat butonuna bastığında evet hayır seceneği cıkması icin gerekli kod.
        int uyarı= JOptionPane.showConfirmDialog(this,"Hesap Tutarı Ödendi mi?","Uyarı!",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(uyarı==JOptionPane.YES_OPTION){
            
            //HESAP ÖDENDİĞİNDE SIFIRLAMAK İCİN CALIŞICAK KOD.
            
           try{
            
            //Veritabanı bağlantısı
            Class.forName(sqlayar.Driver);
            Connection con=DriverManager.getConnection(sqlayar.url, sqlayar.user, sqlayar.pass);
         
            String sql="update Masalar set fiyat=? where Masano=?";  //sorgu
            
            //hesaba fiyat ekleme
           
           
        
            PreparedStatement pst=con.prepareStatement(sql);
             pst.setString(1,"0");
             pst.setString(2,masaaditxt.getText());
             
            
             String name=hesaptxt.getText();
              if(name.equals("")){//eklenicek fiyat boş ise uyarı vericek.
                   JOptionPane.showMessageDialog(this,"Hangi masanın hesabını silmeliyim Lütfen tablodan seciniz. ");
              }
              else if(name.equals("0")){
                  JOptionPane.showMessageDialog(this,"Hesap tutarı zaten 0 TL. ");
              }
              else{//masa ya hesap eklenmede bi sıkıntı yoksa calışıcak kodlar
              pst.executeUpdate();
               DefaultTableModel model= (DefaultTableModel)masabilgitbl.getModel();
             model.setRowCount(0);
             hesaptxt.setText("0");
              show_masa();
            
              }
        }catch(Exception e){
             JOptionPane.showMessageDialog(this,e.getMessage());//eğer bir hata alırsak calışıcak kod.
        }
        }
        
        
       
    }//GEN-LAST:event_hesapkapatbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IslemPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IslemPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IslemPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IslemPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IslemPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adettxt;
    private javax.swing.JLabel cikismasa;
    private javax.swing.JTextField fiyattxt;
    private javax.swing.JLabel girisgit;
    private javax.swing.JButton hesapekle;
    private javax.swing.JButton hesapkapatbtn;
    private javax.swing.JTextField hesaptxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField masaaditxt;
    private javax.swing.JTable masabilgitbl;
    private javax.swing.JTable uruntbl;
    private javax.swing.JTextField uruntxt;
    // End of variables declaration//GEN-END:variables

}
