/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package restoransistemi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ewnS
 */
public class Urunayarları extends javax.swing.JFrame {

   int mouseX;
   int mouseY;
    public Urunayarları() {
        initComponents();
        show_urun();
    }

      sqlsettings sqlayar =new sqlsettings();
    
    public ArrayList<urunler> urunList(){
            ArrayList<urunler> urunList= new ArrayList<>();
         try{
            Class.forName(sqlayar.Driver);
            Connection con=DriverManager.getConnection(sqlayar.url, sqlayar.user, sqlayar.pass);
            String sqlsorgu="Select * from ürünler ";  
          
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(sqlsorgu);
         
            urunler urun;
          
            while(rs.next()){
                urun=new urunler(rs.getString("urunbilgisi"),rs.getInt("fiyat"));
           urunList.add(urun);
            }

        }catch(Exception e){
             JOptionPane.showMessageDialog(this,e.getMessage());
        }
         return urunList;
    }
        public void show_urun(){
        ArrayList<urunler> list= urunList();
        DefaultTableModel model= (DefaultTableModel)uruntbl.getModel();
        Object[] row= new Object[2];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).geturun();
            row[1]=list.get(i).gethesap();
            model.addRow(row);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        uruntxt = new javax.swing.JTextField();
        eklebtn = new javax.swing.JButton();
        fiyattxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        uruntbl = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        fiyatguncelletxt = new javax.swing.JTextField();
        fiyatguncellemebtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        acıklamaguncelletxt = new javax.swing.JTextField();
        acıklamaguncellebtn = new javax.swing.JButton();
        silbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cikismasa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Masalar");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Ürün hakkında acıklama gir:");

        uruntxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        uruntxt.setForeground(new java.awt.Color(51, 51, 51));
        uruntxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        eklebtn.setBackground(new java.awt.Color(204, 59, 16));
        eklebtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        eklebtn.setForeground(new java.awt.Color(255, 255, 255));
        eklebtn.setText("Ekle");
        eklebtn.setBorder(null);
        eklebtn.setBorderPainted(false);
        eklebtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eklebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eklebtnActionPerformed(evt);
            }
        });

        fiyattxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        fiyattxt.setForeground(new java.awt.Color(51, 51, 51));
        fiyattxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Fiyat:");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Ürün hakkında acıklama yazarken kücük harf ile  yazmaya özen gösterin.");

        uruntbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ürün Hakkında", "Fiyat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(uruntbl);
        if (uruntbl.getColumnModel().getColumnCount() > 0) {
            uruntbl.getColumnModel().getColumn(0).setMinWidth(350);
            uruntbl.getColumnModel().getColumn(0).setMaxWidth(350);
        }

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Güncelleme Paneli", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 59, 16))); // NOI18N
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Fiyatı Güncelle:");

        fiyatguncelletxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        fiyatguncelletxt.setForeground(new java.awt.Color(51, 51, 51));
        fiyatguncelletxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        fiyatguncellemebtn.setBackground(new java.awt.Color(204, 59, 16));
        fiyatguncellemebtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        fiyatguncellemebtn.setForeground(new java.awt.Color(255, 255, 255));
        fiyatguncellemebtn.setText("Güncelle");
        fiyatguncellemebtn.setBorder(null);
        fiyatguncellemebtn.setBorderPainted(false);
        fiyatguncellemebtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fiyatguncellemebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiyatguncellemebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel4)
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fiyatguncelletxt)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(fiyatguncellemebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(fiyatguncelletxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fiyatguncellemebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Acıklamayı Güncelle:");

        acıklamaguncelletxt.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        acıklamaguncelletxt.setForeground(new java.awt.Color(51, 51, 51));
        acıklamaguncelletxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        acıklamaguncellebtn.setBackground(new java.awt.Color(204, 59, 16));
        acıklamaguncellebtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        acıklamaguncellebtn.setForeground(new java.awt.Color(255, 255, 255));
        acıklamaguncellebtn.setText("Güncelle");
        acıklamaguncellebtn.setBorder(null);
        acıklamaguncellebtn.setBorderPainted(false);
        acıklamaguncellebtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        acıklamaguncellebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acıklamaguncellebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel3)
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(acıklamaguncellebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(acıklamaguncelletxt)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(acıklamaguncellebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(acıklamaguncelletxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(66, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(118, 118, 118))
        );

        silbtn.setBackground(new java.awt.Color(204, 59, 16));
        silbtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        silbtn.setForeground(new java.awt.Color(255, 255, 255));
        silbtn.setText("Sil");
        silbtn.setBorder(null);
        silbtn.setBorderPainted(false);
        silbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        silbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(fiyattxt))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(uruntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(eklebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(silbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(uruntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fiyattxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eklebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(silbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 59, 16));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        cikismasa.setBackground(new java.awt.Color(204, 59, 16));
        cikismasa.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        cikismasa.setForeground(new java.awt.Color(255, 255, 255));
        cikismasa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cikismasa.setText("x");
        cikismasa.setOpaque(true);
        cikismasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cikismasaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cikismasa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(cikismasa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(772, 545));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cikismasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cikismasaMouseClicked

            this.setVisible(false);
        
    }//GEN-LAST:event_cikismasaMouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int kordinatX=evt.getXOnScreen();
        int kordinatY=evt.getYOnScreen();
        
        this.setLocation(kordinatX-mouseX,kordinatY-mouseY);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
       mouseX=evt.getX();
       mouseY=evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void eklebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eklebtnActionPerformed
 try{
            Class.forName(sqlayar.Driver);
            Connection con=DriverManager.getConnection(sqlayar.url, sqlayar.user, sqlayar.pass);
            String sql="insert into ürünler"+"(urunbilgisi,fiyat)"+"values(?,?)";
            
            PreparedStatement pst=con.prepareStatement(sql);
       
             pst.setString(1,uruntxt.getText());
              pst.setString(2,fiyattxt.getText());
            
              
              String masa=uruntxt.getText();
              String fiyat=fiyattxt.getText();
              if(masa.equals("")|| fiyat.equals("") ){
                   JOptionPane.showMessageDialog(this,"Acıklamayı yada fiyatı boş bırakamazsın. ");
              }
              else{
                  pst.executeUpdate();
                    DefaultTableModel model= (DefaultTableModel)uruntbl.getModel();
            
             model.setNumRows(0);
             
              show_urun();
              uruntxt.setText("");
              fiyattxt.setText("");
              JOptionPane.showMessageDialog(this,"Yeni Ürün oluşturuldu.");}
        }catch(Exception e){
             JOptionPane.showMessageDialog(this,e.getMessage());
        }
        
    }//GEN-LAST:event_eklebtnActionPerformed

    private void silbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silbtnActionPerformed
         try{
            Class.forName(sqlayar.Driver);
            Connection con=DriverManager.getConnection(sqlayar.url, sqlayar.user, sqlayar.pass);
            String sql="Delete from ürünler where urunbilgisi=?";
            
            PreparedStatement pst=con.prepareStatement(sql);
             pst.setString(1,uruntxt.getText());
            
            
            
              pst.executeUpdate();
                DefaultTableModel model= (DefaultTableModel)uruntbl.getModel();
             model.setNumRows(0);
             
              show_urun();
              JOptionPane.showMessageDialog(this,"Ürün başarılı bir şekilde silindi. ");
        }catch(Exception e){
             JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_silbtnActionPerformed

    private void fiyatguncellemebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiyatguncellemebtnActionPerformed
       try{
            Class.forName(sqlayar.Driver);
            Connection con=DriverManager.getConnection(sqlayar.url, sqlayar.user, sqlayar.pass);
            String sql="update ürünler set fiyat=? where urunbilgisi=?";
            
            PreparedStatement pst=con.prepareStatement(sql);
             pst.setString(2,uruntxt.getText());
              pst.setString(1,fiyatguncelletxt.getText());
            
             String name=uruntxt.getText();
              if(name.equals("")){
                   JOptionPane.showMessageDialog(this,"Ürün adı boş bırakılamaz. ");
              }
              else{
              pst.executeUpdate();
              DefaultTableModel model= (DefaultTableModel)uruntbl.getModel();
              model.setNumRows(0);
              show_urun();
              uruntxt.setText("");
              acıklamaguncelletxt.setText("");
              fiyatguncelletxt.setText("");
              JOptionPane.showMessageDialog(this,"Urun fiyatı başarılı bir şekilde değiştirildi. ");
              }
        }catch(Exception e){
             JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_fiyatguncellemebtnActionPerformed

    private void acıklamaguncellebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acıklamaguncellebtnActionPerformed
          
        try{
            Class.forName(sqlayar.Driver);
            Connection con=DriverManager.getConnection(sqlayar.url, sqlayar.user,sqlayar.pass);
            String sql="update ürünler set urunbilgisi=? where urunbilgisi=?";
            
            PreparedStatement pst=con.prepareStatement(sql);
             pst.setString(2,uruntxt.getText());
              pst.setString(1,acıklamaguncelletxt.getText());
            
             String name=uruntxt.getText();
              if(name.equals("")){
                   JOptionPane.showMessageDialog(this,"Urun adı boş bırakılamaz. ");
              }
              else{
              pst.executeUpdate();
              DefaultTableModel model= (DefaultTableModel)uruntbl.getModel();
              model.setNumRows(0);
              show_urun();
              uruntxt.setText("");
              acıklamaguncelletxt.setText("");
              JOptionPane.showMessageDialog(this,"Urun ismi başarılı bir şekilde değiştirildi. ");
              }
        }catch(Exception e){
             JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_acıklamaguncellebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Urunayarları.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Urunayarları.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Urunayarları.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Urunayarları.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Urunayarları().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acıklamaguncellebtn;
    private javax.swing.JTextField acıklamaguncelletxt;
    private javax.swing.JLabel cikismasa;
    private javax.swing.JButton eklebtn;
    private javax.swing.JButton fiyatguncellemebtn;
    private javax.swing.JTextField fiyatguncelletxt;
    private javax.swing.JTextField fiyattxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton silbtn;
    private javax.swing.JTable uruntbl;
    private javax.swing.JTextField uruntxt;
    // End of variables declaration//GEN-END:variables

}
